"""
RAG Faithfulness & Quality Evaluation — LLM-as-Judge
=====================================================
Scores each RAG response across four dimensions using the same local LLM
(Ollama) as a judge. This is the hand-rolled, dependency-free evaluator; for
the industry-standard library metrics see ``evaluate_rag_ragas.py``. Both
evaluators share the cached generations produced by ``_eval_common.py``, so the
pipeline only runs once.

Usage (from project root, venv activated, Ollama running):
    python scripts/evaluate_rag_faithfulness.py
    python scripts/evaluate_rag_faithfulness.py --refresh   # ignore prediction cache

Output:
    processed/rag_eval_report.json   — full results per question
    processed/rag_eval_summary.txt   — printable table for your report
"""

import json
import re
import sys
import time
from pathlib import Path

# ── path setup ──────────────────────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from _eval_common import generate_predictions, parse_refresh_flag  # noqa: E402
from backend.llm import LLMError, run_llm  # noqa: E402

# ── config ──────────────────────────────────────────────────────────────────
OUT_JSON = ROOT / "processed" / "rag_eval_report.json"
OUT_TXT = ROOT / "processed" / "rag_eval_summary.txt"
SLEEP_SEC = 0.5   # pause between LLM judge calls


# ── score parsing ─────────────────────────────────────────────────────────────

def _parse_score(prompt: str) -> float:
    """
    Call the LLM judge and extract a 0.0–1.0 score robustly.
    Handles:
      - Clean JSON:          {"score": 0.8, "reason": "..."}
      - JSON buried in text: "Here is my rating: {"score": 0.7}"
      - Plain number:        "0.8" / "Score: 0.75"
      - Missing "score" key: tries "result", "rating", "value"
    """
    try:
        time.sleep(SLEEP_SEC)
        raw = run_llm(prompt)
        raw = raw.strip()

        # 1. Try clean JSON parse
        try:
            obj = json.loads(raw)
            val = obj.get("score", obj.get("result", obj.get("rating", obj.get("value"))))
            if val is not None:
                return max(0.0, min(1.0, float(val)))
        except (json.JSONDecodeError, ValueError, TypeError):
            pass

        # 2. Extract first {...} block and parse that
        start = raw.find("{")
        end   = raw.rfind("}")
        if start != -1 and end > start:
            try:
                obj = json.loads(raw[start:end + 1])
                val = obj.get("score", obj.get("result", obj.get("rating", obj.get("value"))))
                if val is not None:
                    return max(0.0, min(1.0, float(val)))
            except (json.JSONDecodeError, ValueError, TypeError):
                pass

        # 3. Regex: find first decimal like 0.75 or 0.8, or standalone 0/1
        m = re.search(r"\b(0\.\d+|1\.0+|[01])\b", raw)
        if m:
            return max(0.0, min(1.0, float(m.group(1))))

    except LLMError as e:
        print(f"  [LLM error] {e}")
    return 0.0


# ── judge functions ───────────────────────────────────────────────────────────

def _judge_faithfulness(context: str, answer: str) -> float:
    """Does every factual claim in the answer come from the context?"""
    if not context.strip() or not answer.strip():
        return 0.0
    prompt = f"""You are a strict medical fact-checker. Reply with ONLY a JSON object.

CONTEXT (retrieved medical text):
{context[:2000]}

ANSWER (generated by the chatbot):
{answer[:800]}

Does every factual claim in the ANSWER appear in or follow directly from the CONTEXT?
Score 1.0 = all claims grounded in context.
Score 0.5 = most claims grounded, 1-2 minor additions.
Score 0.0 = answer contradicts context or invents facts not present.

Reply with ONLY: {{"score": <number between 0.0 and 1.0>, "reason": "<one sentence>"}}"""
    return _parse_score(prompt)


def _judge_answer_relevance(question: str, answer: str) -> float:
    """Does the answer actually address the question?"""
    if not answer.strip():
        return 0.0
    prompt = f"""You are evaluating a dermatology chatbot. Reply with ONLY a JSON object.

QUESTION: {question}

ANSWER: {answer[:800]}

How well does the ANSWER address the QUESTION?
Score 1.0 = directly and fully answers the question.
Score 0.5 = partially relevant but incomplete or off-topic in parts.
Score 0.0 = does not answer the question (says it lacks information, or asks for body location instead of answering).

Reply with ONLY: {{"score": <number between 0.0 and 1.0>, "reason": "<one sentence>"}}"""
    return _parse_score(prompt)


def _judge_context_relevance(question: str, context: str) -> float:
    """Is the retrieved context actually relevant to the question?"""
    if not context.strip():
        return 0.0
    prompt = f"""You are evaluating a medical retrieval system. Reply with ONLY a JSON object.

QUESTION: {question}

RETRIEVED CONTEXT:
{context[:2000]}

How relevant is the RETRIEVED CONTEXT to answering the QUESTION?
Score 1.0 = context directly contains information needed to answer.
Score 0.5 = context is from the same medical domain but only partially relevant.
Score 0.0 = context is about a completely different condition or topic.

Reply with ONLY: {{"score": <number between 0.0 and 1.0>, "reason": "<one sentence>"}}"""
    return _parse_score(prompt)


def _judge_keyword_coverage(answer: str, keywords: list) -> float:
    """Fraction of expected medical keywords present in the answer."""
    if not keywords or not answer:
        return 0.0
    answer_l = answer.lower()
    hits = sum(1 for kw in keywords if kw.lower() in answer_l)
    return round(hits / len(keywords), 2)


# ── main evaluation loop ──────────────────────────────────────────────────────

def run_evaluation() -> None:
    print("=" * 60)
    print("  DermaRAG — LLM-as-Judge Evaluation")
    print("=" * 60)

    refresh = parse_refresh_flag(sys.argv)
    predictions = generate_predictions(use_cache=not refresh)

    results = []
    totals = {
        "faithfulness":     0.0,
        "answer_relevance": 0.0,
        "context_relevance":0.0,
        "keyword_coverage": 0.0,
        "response_time_s":  0.0,
    }

    for i, pred in enumerate(predictions, 1):
        qid      = pred["id"]
        question = pred["question"]
        keywords = pred.get("expected_keywords", [])
        lang     = pred.get("language", "en")
        answer   = pred["answer"]
        context  = pred["context_str"]
        response_time_s = pred["response_time_s"]

        print(f"\n[{i}/{len(predictions)}] {qid}: {question}")
        print(f"  Response time: {response_time_s}s")
        print(f"  Answer: {answer[:120]}...")

        no_answer  = pred["no_answer"]
        no_context = not context.strip()

        if no_answer:
            print("  [skipped] Pipeline returned no answer — scoring 0 on all LLM metrics")
            faith   = 0.0
            ans_rel = 0.0
            ctx_rel = 0.0
        else:
            # ── LLM judge scores ────────────────────────────────────────────
            print("  Scoring faithfulness...", end=" ", flush=True)
            # Only meaningful when we have real retrieved context
            faith = _judge_faithfulness(context, answer) if not no_context else 0.0
            print(f"{faith:.2f}")

            print("  Scoring answer relevance...", end=" ", flush=True)
            ans_rel = _judge_answer_relevance(question, answer)
            print(f"{ans_rel:.2f}")

            print("  Scoring context relevance...", end=" ", flush=True)
            ctx_rel = _judge_context_relevance(question, context) if not no_context else 0.0
            print(f"{ctx_rel:.2f}")

        kw_cov = _judge_keyword_coverage(answer, keywords)
        print(f"  Keyword coverage: {kw_cov:.2f} "
              f"({int(kw_cov * len(keywords))}/{len(keywords)} keywords)")

        row = {
            "id":                qid,
            "language":          lang,
            "question":          question,
            "answer":            answer,
            "faithfulness":      faith,
            "answer_relevance":  ans_rel,
            "context_relevance": ctx_rel,
            "keyword_coverage":  kw_cov,
            "response_time_s":   response_time_s,
            "no_answer":         no_answer,
            "context_snippet":   context[:300],
        }
        results.append(row)

        for k in totals:
            totals[k] += row[k]

    n = len(results)
    avg_keys = ["faithfulness", "answer_relevance", "context_relevance",
                "keyword_coverage", "response_time_s"]
    averages = {k: round(totals[k] / n, 3) for k in avg_keys}
    averages["avg_response_time_s"] = averages.pop("response_time_s")
    averages["total_eval_time_s"]   = round(totals["response_time_s"], 1)

    # ── save JSON report ──────────────────────────────────────────────────────
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    report = {"cases": results, "averages": averages, "n": n}
    with open(OUT_JSON, "w", encoding="utf-8") as f:
        json.dump(report, f, ensure_ascii=False, indent=2)
    print(f"\nFull report saved → {OUT_JSON}")

    # ── print summary table ───────────────────────────────────────────────────
    col = [8, 34, 12, 14, 16, 14, 10]
    sep = "+" + "+".join("-" * c for c in col) + "+"
    hdr = (f"| {'ID':<6} | {'Question':<32} | {'Faithful':^10} | "
           f"{'Ans.Relev.':^12} | {'Ctx.Relev.':^14} | {'Kw.Cover.':^12} | {'Time(s)':^8} |")
    lines = [sep, hdr, sep]
    for r in results:
        flag = "!" if r["no_answer"] else " "
        lines.append(
            f"|{flag}{r['id']:<6} | {r['question'][:32]:<32} | {r['faithfulness']:^10.2f} | "
            f"{r['answer_relevance']:^12.2f} | {r['context_relevance']:^14.2f} | "
            f"{r['keyword_coverage']:^12.2f} | {r['response_time_s']:^8.1f} |"
        )
    lines.append(sep)
    lines.append(
        f"| {'AVG':<6} | {'':<32} | {averages['faithfulness']:^10.2f} | "
        f"{averages['answer_relevance']:^12.2f} | {averages['context_relevance']:^14.2f} | "
        f"{averages['keyword_coverage']:^12.2f} | {averages['avg_response_time_s']:^8.1f} |"
    )
    lines.append(sep)
    lines.append("  ! = pipeline returned no answer (slot gate or missing chunks)")

    table = "\n".join(lines)
    print("\n" + table)

    with open(OUT_TXT, "w", encoding="utf-8") as f:
        f.write("DermaRAG — RAG Quality Evaluation Results\n")
        f.write("Evaluation method: LLM-as-Judge (local Ollama)\n")
        f.write(f"Questions evaluated: {n}  "
                f"({sum(1 for r in results if r['language'] == 'en')} EN, "
                f"{sum(1 for r in results if r['language'] == 'tr')} TR)\n")
        f.write(f"No-answer cases:     "
                f"{sum(1 for r in results if r['no_answer'])} "
                f"(marked with ! in table)\n\n")
        f.write(table + "\n\n")
        f.write("Metric definitions:\n")
        f.write("  Faithfulness      — Every answer claim is supported by retrieved context\n")
        f.write("                      (0 = hallucination, 1 = fully grounded)\n")
        f.write("  Answer Relevance  — Answer addresses the question asked\n")
        f.write("                      (0 = irrelevant/no-answer, 1 = fully answers)\n")
        f.write("  Context Relevance — Retrieved chunks relevant to the question\n")
        f.write("                      (0 = wrong topic, 1 = on-topic)\n")
        f.write("  Keyword Coverage  — Expected medical terms present in answer\n")
        f.write("  Response Time     — End-to-end pipeline latency (seconds)\n")

    print(f"\nSummary saved → {OUT_TXT}")
    print(f"\n{'=' * 60}")
    print(f"  AVERAGES  (n={n}, "
          f"no-answer cases={sum(1 for r in results if r['no_answer'])})")
    print(f"  Faithfulness:        {averages['faithfulness']:.2f}")
    print(f"  Answer Relevance:    {averages['answer_relevance']:.2f}")
    print(f"  Context Relevance:   {averages['context_relevance']:.2f}")
    print(f"  Keyword Coverage:    {averages['keyword_coverage']:.2f}")
    print(f"  Avg Response Time:   {averages['avg_response_time_s']:.1f}s per query")
    print(f"  Total Pipeline Time: {averages['total_eval_time_s']:.1f}s")
    print(f"{'=' * 60}")
    print("\n  Target benchmarks:")
    print("  ≥ 0.70 = Acceptable   ≥ 0.80 = Good   ≥ 0.85 = Strong")


if __name__ == "__main__":
    run_evaluation()
